import "@shlz/styles";
import "./showcase.css";
import tokens from "@shlz/tokens/tokens.json";
import provenance from "@shlz/tokens/provenance.json";
import manifest from "@shlz/icons/manifest.json";
import {
  enhanceDrawers,
  enhanceDropdowns,
  enhanceModals,
  enhancePopovers,
  enhanceTabs,
  enhanceTooltips,
} from "@shlz/behaviors";

const iconUrls = import.meta.glob(
  "../../../packages/icons/dist/{icons,file-types}/*.svg",
  {
    eager: true,
    query: "?url",
    import: "default",
  },
);

const app = document.querySelector("#app");
const evidenceLabel = (item) =>
  `<span class="shlz-evidence" data-kind="${item.classification}">${item.classification} · ${item.confidence}</span>`;
const sourceEvidence = evidenceLabel(provenance.layers.source);
const semanticEvidence = evidenceLabel(provenance.layers.semantic);
const colors = Object.entries(tokens.source.color)
  .map(
    ([group, values]) =>
      `<article class="shlz-source-group"><h3>${group}</h3><div class="shlz-source-swatches">${Object.entries(
        values,
      )
        .map(
          ([name, value]) =>
            `<div class="shlz-swatch"><i style="--shlz-swatch:${value}"></i><b>${name}</b><code>${value}</code></div>`,
        )
        .join("")}</div></article>`,
  )
  .join("");
const spaces = Object.entries(tokens.source.spacing)
  .map(
    ([name, value]) =>
      `<div class="shlz-measure"><i style="inline-size:${value}"></i><code>${name} · ${value}</code></div>`,
  )
  .join("");
const radii = Object.entries(tokens.source.radius)
  .map(
    ([name, value]) =>
      `<div class="shlz-radius" style="border-radius:${value}"><b>${name}</b><code>${value}</code></div>`,
  )
  .join("");
const iconCards = manifest
  .map(({ name, file, colorMode, uncertainty }) => {
    const url = Object.entries(iconUrls).find(([source]) =>
      source.endsWith(file),
    )?.[1];
    return `<figure class="shlz-icon-card" title="${uncertainty ?? ""}"><img src="${url}" alt=""/><figcaption>${name}<small>${colorMode}</small></figcaption></figure>`;
  })
  .join("");

const modalLongContent = Array.from(
  { length: 12 },
  (_, index) => `<p>Строка длинного содержимого ${index + 1}</p>`,
).join("");
const drawerLongContent = Array.from(
  { length: 24 },
  (_, index) => `<p>Прокручиваемая строка ${index + 1}</p>`,
).join("");
const overlayDemos = `
<article id="modal-demo"><h3>Modal</h3><p><code>Modal.svg</code> · <span class="shlz-evidence" data-kind="FACT">FACT · 572px, radius 16, structured regions</span> <span class="shlz-evidence" data-kind="DECISION">DECISION · native dialog, opt-in backdrop dismissal</span></p><div class="shlz-cluster"><button class="shlz-button shlz-button--primary" type="button" data-shlz-modal-trigger="showcase-modal">Открыть Modal</button><button class="shlz-button" type="button" data-shlz-modal-trigger="showcase-confirm">Подтверждение</button></div>
<dialog class="shlz-modal" id="showcase-modal" data-shlz-modal data-shlz-modal-backdrop-close aria-labelledby="showcase-modal-title"><div class="shlz-modal__surface"><header class="shlz-modal__header"><h2 class="shlz-modal__title" id="showcase-modal-title">Заголовок Modal</h2><button class="shlz-modal__close" type="button" data-shlz-modal-close aria-label="Закрыть">×</button></header><div class="shlz-modal__body"><div class="shlz-stack"><label class="shlz-field"><span class="shlz-field__label">Название</span><input class="shlz-input" id="modal-autofocus" autofocus value="Native dialog"></label><p>Body прокручивается независимо от header и footer. Ниже проверяются floating-компоненты внутри top layer.</p><div class="shlz-cluster"><div class="shlz-dropdown" data-shlz-dropdown><button class="shlz-button shlz-button--sm" type="button" aria-haspopup="menu" aria-expanded="false" aria-controls="modal-menu">Dropdown внутри Modal</button><div class="shlz-dropdown__menu" id="modal-menu" role="menu" hidden><button class="shlz-dropdown__item" type="button" role="menuitem">Первый пункт</button><button class="shlz-dropdown__item" type="button" role="menuitem">Второй пункт</button></div></div><button class="shlz-button shlz-button--sm" type="button" data-shlz-tooltip-trigger="modal-tooltip" data-shlz-tooltip-open-delay="0">Tooltip внутри Modal</button><div class="shlz-tooltip" id="modal-tooltip" role="tooltip" data-shlz-tooltip hidden>Подсказка<span class="shlz-tooltip__arrow" aria-hidden="true"></span></div><button class="shlz-button shlz-button--sm" type="button" aria-expanded="false" aria-controls="modal-popover" data-shlz-popover-trigger="modal-popover" data-shlz-popover-placement="bottom">Popover внутри Modal</button><div class="shlz-popover" id="modal-popover" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Вложенный Popover</div><div class="shlz-popover__body">Escape сначала закрывает floating surface.</div></div></div><div class="shlz-modal-long-content" data-modal-long-content>${modalLongContent}</div></div></div><footer class="shlz-modal__footer"><button class="shlz-button" type="button" data-shlz-modal-close>Отмена</button><button class="shlz-button shlz-button--primary" type="button" data-shlz-modal-close="save">Сохранить</button></footer></div></dialog>
<dialog class="shlz-modal shlz-modal--compact" id="showcase-confirm" data-shlz-modal aria-labelledby="showcase-confirm-title"><form class="shlz-modal__surface" method="dialog"><div class="shlz-modal__body"><h2 class="shlz-modal__title" id="showcase-confirm-title">Подтвердить действие?</h2><p>Для confirm/cancel доступна нативная форма <code>method=&quot;dialog&quot;</code>.</p></div><footer class="shlz-modal__footer"><button class="shlz-button" value="cancel">Отмена</button><button class="shlz-button shlz-button--primary" value="confirm">Подтвердить</button></footer></form></dialog></article>
<article id="drawer-demo"><h3>Drawer</h3><p><code>Drawer.svg</code> · <span class="shlz-evidence" data-kind="FACT">FACT · 420×900, 64/764/72 regions</span> <span class="shlz-evidence" data-kind="DECISION">DECISION · modal right-side native dialog</span></p><button class="shlz-button shlz-button--primary" type="button" data-shlz-drawer-trigger="showcase-drawer">Открыть Drawer</button><dialog class="shlz-drawer" id="showcase-drawer" data-shlz-drawer data-shlz-drawer-backdrop-close aria-labelledby="showcase-drawer-title"><div class="shlz-drawer__surface"><header class="shlz-drawer__header"><h2 class="shlz-drawer__title" id="showcase-drawer-title">Заголовок Drawer</h2><button class="shlz-drawer__close" type="button" data-shlz-drawer-close aria-label="Закрыть">×</button></header><div class="shlz-drawer__body" data-drawer-scroll><div class="shlz-stack"><label class="shlz-field"><span class="shlz-field__label">Параметр</span><input class="shlz-input" autofocus></label><p>Drawer использует ту же native modal lifecycle, но независимую source-derived geometry.</p>${drawerLongContent}</div></div><footer class="shlz-drawer__footer"><button class="shlz-button" type="button" data-shlz-drawer-close>Отмена</button><button class="shlz-button shlz-button--primary" type="button" data-shlz-drawer-close="apply">Применить</button></footer></div></dialog></article>`;

app.innerHTML = `<header class="shlz-hero"><p>SHLZ UI · source-spec reset</p><h1>Source specification and implementation fidelity</h1><p>Специализированные Figma sheets отделены от инженерных aliases и component-specific geometry.</p></header>
<section id="source-spec" class="shlz-major-section"><p class="shlz-section-kicker">A. SOURCE SPEC</p><h2>Буквальная спецификация Figma ${sourceEvidence}</h2><p><code>Colors.svg</code>, <code>Spacing.svg</code> и human-verified Corner radius source. Имена, группы и значения не нормализованы в искусственные шкалы.</p>
<div class="shlz-source-sheet"><h2>Colors</h2><div class="shlz-source-palette">${colors}</div></div>
<div class="shlz-source-sheet shlz-source-sheet--split"><div><h2>Spacing</h2><div class="shlz-stack">${spaces}</div></div><div><h2>Corner radius</h2><div class="shlz-radius-grid">${radii}</div></div></div>
<div class="shlz-source-sheet"><h2>Typography</h2><p class="shlz-type-sample">Аа Бб 0123 — явный system sans stack</p><p>${semanticEvidence} Точная гарнитура не восстанавливается из outlined text; браузерный serif запрещён.</p></div></section>
<section id="implementation" class="shlz-major-section"><p class="shlz-section-kicker">B. IMPLEMENTATION</p><h2>Production library</h2><section><h3>Semantic aliases ${semanticEvidence}</h3><div class="shlz-cluster"><div class="shlz-demo-surface">surface.base / text.primary</div><div class="shlz-demo-action">action.primary</div><div class="shlz-demo-status">status.success</div><div class="shlz-demo-danger">status.danger</div></div></section><section><h3>Control geometry</h3><div class="shlz-cluster"><input class="shlz-control" aria-label="Пример поля" value="40 px control"/><button class="shlz-control shlz-focusable">Focus me</button><button class="shlz-control" data-size="sm">32 px</button><button class="shlz-control" disabled>Disabled</button></div></section>
<section id="components"><h2>Components <span class="shlz-evidence" data-kind="FACT">FACT · component sheets</span></h2>
<article><h3>Button</h3><p><code>Buttons.svg</code> · 26/32/40 px, primary/neutral, icon forms.</p><div class="shlz-cluster"><button class="shlz-button shlz-button--primary">Создать</button><button class="shlz-button">Отмена</button><button class="shlz-button shlz-button--primary shlz-button--sm">32 px</button><button class="shlz-button shlz-button--xs">26 px</button><button class="shlz-button shlz-button--primary shlz-button--icon" aria-label="Добавить">+</button><button class="shlz-button shlz-button--primary" disabled>Недоступно</button></div></article>
<article><h3>Input and textarea</h3><p><code>Select.svg</code>, <code>Input Number.svg</code>, <code>Textarea.svg</code> · input-like geometry only.</p><div class="shlz-component-grid"><label class="shlz-field"><span class="shlz-field__label">Название</span><input class="shlz-input" placeholder="Введите название"></label><label class="shlz-field"><span class="shlz-field__label">32 px</span><input class="shlz-input shlz-input--sm" value="Заполнено"></label><label class="shlz-field"><span class="shlz-field__label">Ошибка</span><input class="shlz-input" aria-invalid="true" value="Некорректно"><span class="shlz-field__message">Проверьте значение</span></label><label class="shlz-field"><span class="shlz-field__label">Комментарий</span><textarea class="shlz-textarea">Длинный текст проверяет перенос и вертикальный ритм.</textarea></label><label class="shlz-field"><span class="shlz-field__label">Disabled</span><input class="shlz-input" disabled value="Недоступно"></label></div></article>
<article><h3>Checkbox, radio and switch</h3><p><code>Checkbox.svg</code>, <code>Radio.svg</code>, <code>Switch.svg</code> · state is owned by native inputs.</p><div class="shlz-cluster"><label class="shlz-choice"><input class="shlz-checkbox" type="checkbox">Unchecked</label><label class="shlz-choice"><input class="shlz-checkbox" type="checkbox" checked>Checked</label><label class="shlz-choice"><input class="shlz-checkbox" data-indeterminate type="checkbox">Indeterminate</label><label class="shlz-choice"><input class="shlz-checkbox" type="checkbox" disabled>Disabled</label></div><fieldset class="shlz-demo-fieldset"><legend>Native radio group</legend><label class="shlz-choice"><input class="shlz-radio" type="radio" name="demo-radio" checked>Первый</label><label class="shlz-choice"><input class="shlz-radio" type="radio" name="demo-radio">Второй</label><label class="shlz-choice"><input class="shlz-radio" type="radio" name="demo-radio" disabled>Disabled</label></fieldset><div class="shlz-cluster"><label class="shlz-switch"><input class="shlz-switch__input shlz-switch__input--sm" type="checkbox" role="switch" checked>Small</label><label class="shlz-switch"><input class="shlz-switch__input" type="checkbox" role="switch">Medium</label><label class="shlz-switch"><input class="shlz-switch__input shlz-switch__input--lg" type="checkbox" role="switch" checked>Large</label></div></article>
<article><h3>Status / Badge</h3><p><code>Status.svg</code>, <code>Bage.svg</code> · color meaning remains UNKNOWN.</p><div class="shlz-cluster"><span class="shlz-status">Blue</span><span class="shlz-status shlz-status--green">Green</span><span class="shlz-status shlz-status--orange">Orange</span><span class="shlz-status shlz-status--purple">Purple</span><span class="shlz-status shlz-status--cyan">Cyan</span><span class="shlz-status shlz-status--neutral">Neutral</span><span class="shlz-badge" aria-label="3 уведомления">3</span><span class="shlz-badge shlz-badge--lg shlz-badge--neutral">12</span></div></article>
<article id="dropdown-demo"><h3>Dropdown menu</h3><p><code>Dropdown menu.svg</code> · FACT: 200/216 px menu, 40 px items, 12 px radius, 20 px icon slots. Highlight semantics remain UNKNOWN.</p><div class="shlz-cluster"><div class="shlz-dropdown" data-shlz-dropdown><button class="shlz-button" type="button" aria-haspopup="menu" aria-expanded="false" aria-controls="showcase-actions">Действия</button><div class="shlz-dropdown__menu" id="showcase-actions" role="menu" hidden><button class="shlz-dropdown__item" type="button" role="menuitem"><span class="shlz-dropdown__icon" aria-hidden="true">＋</span>Создать</button><button class="shlz-dropdown__item" type="button" role="menuitem" aria-current="true"><span class="shlz-dropdown__icon" aria-hidden="true">✓</span>Текущий пункт</button><hr class="shlz-dropdown__separator" role="separator"><button class="shlz-dropdown__item" type="button" role="menuitem" disabled>Недоступно</button><button class="shlz-dropdown__item" type="button" role="menuitem">Длинный пункт меню для проверки ширины</button></div></div><div class="shlz-dropdown" data-shlz-dropdown><button class="shlz-button shlz-button--primary" type="button" aria-haspopup="menu" aria-expanded="false" aria-controls="showcase-wide-actions">Широкое меню</button><div class="shlz-dropdown__menu shlz-dropdown__menu--wide" id="showcase-wide-actions" role="menu" hidden><button class="shlz-dropdown__item" type="button" role="menuitem">Первый пункт</button><button class="shlz-dropdown__item" type="button" role="menuitem">Второй пункт</button></div></div></div></article>
<article id="popover-demo"><h3>Popover</h3><p><code>Popover.svg</code> · <span class="shlz-evidence" data-kind="FACT">FACT · 236×90, radius 12, four sides</span> <span class="shlz-evidence" data-kind="DECISION">DECISION · 8px offset, flip/shift</span></p><div class="shlz-popover-lab">
<div><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-bottom" data-shlz-popover-trigger="popover-bottom" data-shlz-popover-placement="bottom">Bottom</button><div class="shlz-popover" id="popover-bottom" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header" id="popover-bottom-title">Заголовок</div><div class="shlz-popover__body">Длинный content переносится, не меняя публичный контракт.</div></div></div>
<div><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-top" data-shlz-popover-trigger="popover-top" data-shlz-popover-placement="top">Top</button><div class="shlz-popover" id="popover-top" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Сверху</div><div class="shlz-popover__body">Предпочтительная сторона сохраняется, пока хватает места.</div></div></div>
<div><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-left" data-shlz-popover-trigger="popover-left" data-shlz-popover-placement="left">Left</button><div class="shlz-popover" id="popover-left" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Слева</div><div class="shlz-popover__body">Floating surface</div></div></div>
<div><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-right" data-shlz-popover-trigger="popover-right" data-shlz-popover-placement="right">Right</button><div class="shlz-popover" id="popover-right" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Справа</div><div class="shlz-popover__body">Floating surface</div></div></div>
</div><div class="shlz-popover-scenarios"><div><button class="shlz-button shlz-button--primary" type="button" aria-expanded="false" aria-controls="popover-interactive" data-shlz-popover-trigger="popover-interactive" data-shlz-popover-placement="bottom-start">Interactive content</button><div class="shlz-popover" id="popover-interactive" data-shlz-popover hidden aria-labelledby="popover-interactive-title"><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header" id="popover-interactive-title">Настройки</div><div class="shlz-popover__body shlz-stack"><label class="shlz-field" for="popover-value"><span class="shlz-field__label">Значение</span><input class="shlz-input shlz-input--sm" id="popover-value"></label><button class="shlz-button shlz-button--sm" type="button" data-shlz-popover-close>Готово</button></div></div></div>
<div class="shlz-popover-edge"><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-edge" data-shlz-popover-trigger="popover-edge" data-shlz-popover-placement="right">Около края</button><div class="shlz-popover" id="popover-edge" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Collision</div><div class="shlz-popover__body">Панель остаётся во viewport.</div></div></div></div>
<div class="shlz-popover-scroll" data-popover-scroll><div class="shlz-popover-scroll__content"><button class="shlz-button" type="button" aria-expanded="false" aria-controls="popover-scroll" data-shlz-popover-trigger="popover-scroll" data-shlz-popover-placement="bottom">Scroll anchor</button><div class="shlz-popover" id="popover-scroll" data-shlz-popover hidden><span class="shlz-popover__arrow" aria-hidden="true"></span><div class="shlz-popover__header">Scroll</div><div class="shlz-popover__body">Позиция следует за trigger.</div></div></div></div></article>
<article id="tooltip-demo"><h3>Tooltip</h3><p><code>Tooltip.svg</code> · <span class="shlz-evidence" data-kind="FACT">FACT · 100×37, radius 8, 8 placements</span> <span class="shlz-evidence" data-kind="DECISION">DECISION · hover/focus, configurable delay</span></p><div class="shlz-floating-lab">
<div><button class="shlz-button" type="button" data-shlz-tooltip-trigger="tooltip-top" data-shlz-tooltip-placement="top" data-shlz-tooltip-open-delay="0">Tooltip top</button><div class="shlz-tooltip" id="tooltip-top" role="tooltip" data-shlz-tooltip hidden>Подсказка<span class="shlz-tooltip__arrow" aria-hidden="true"></span></div></div>
<div><button class="shlz-button" type="button" data-shlz-tooltip-trigger="tooltip-bottom-start" data-shlz-tooltip-placement="bottom-start" data-shlz-tooltip-open-delay="0">Tooltip bottom start</button><div class="shlz-tooltip" id="tooltip-bottom-start" role="tooltip" data-shlz-tooltip hidden>Подсказка<span class="shlz-tooltip__arrow" aria-hidden="true"></span></div></div>
<div><button class="shlz-button" type="button" data-shlz-tooltip-trigger="tooltip-left" data-shlz-tooltip-placement="left" data-shlz-tooltip-open-delay="0">Tooltip left</button><div class="shlz-tooltip" id="tooltip-left" role="tooltip" data-shlz-tooltip hidden>Подсказка<span class="shlz-tooltip__arrow" aria-hidden="true"></span></div></div>
<div><button class="shlz-button" type="button" data-shlz-tooltip-trigger="tooltip-right" data-shlz-tooltip-placement="right" data-shlz-tooltip-open-delay="0">Tooltip right</button><div class="shlz-tooltip" id="tooltip-right" role="tooltip" data-shlz-tooltip hidden>Длинный текст подсказки проверяет перенос у края viewport.<span class="shlz-tooltip__arrow" aria-hidden="true"></span></div></div>
</div></article>
<article id="tabs-demo"><h3>Tabs</h3><p><code>Tabs.svg</code> · underline, pill and boxed visual families. Automatic activation is a DECISION.</p><div class="shlz-component-grid"><div class="shlz-tabs" data-shlz-tabs><div class="shlz-tabs__list" role="tablist" aria-label="Разделы"><button class="shlz-tabs__tab" id="tab-one" type="button" role="tab" aria-selected="true" aria-controls="panel-one">Первый</button><button class="shlz-tabs__tab" id="tab-two" type="button" role="tab" aria-selected="false" aria-controls="panel-two">Второй</button><button class="shlz-tabs__tab" type="button" role="tab" aria-disabled="true">Disabled</button></div><div class="shlz-tabs__panel" id="panel-one" role="tabpanel" aria-labelledby="tab-one">Содержимое первой панели</div><div class="shlz-tabs__panel" id="panel-two" role="tabpanel" aria-labelledby="tab-two" hidden>Содержимое второй панели с длинным текстом.</div></div><div class="shlz-tabs shlz-tabs--pill"><div class="shlz-tabs__list" role="tablist" aria-label="Визуальные варианты"><button class="shlz-tabs__tab" type="button" role="tab" aria-selected="true">Активный</button><button class="shlz-tabs__tab" type="button" role="tab" aria-selected="false">Обычный</button></div></div><div class="shlz-tabs shlz-tabs--boxed"><div class="shlz-tabs__list" role="tablist" aria-label="Boxed"><button class="shlz-tabs__tab" type="button" role="tab" aria-selected="true">Выбран</button><button class="shlz-tabs__tab" type="button" role="tab" aria-selected="false">Другой</button></div></div></div></article>
<article id="pagination-demo"><h3>Pagination</h3><p><code>Pagination.svg</code> and <code>Pagination (2).svg</code> · native links, 40px controls.</p><nav class="shlz-pagination" aria-label="Пагинация примера"><ul class="shlz-pagination__list"><li><span class="shlz-pagination__item shlz-pagination__item--disabled" aria-disabled="true">‹</span></li><li><a class="shlz-pagination__item" href="#page-1" aria-current="page">1</a></li><li><a class="shlz-pagination__item" href="#page-2">2</a></li><li><a class="shlz-pagination__item" href="#page-3">3</a></li><li><span class="shlz-pagination__item shlz-pagination__item--ellipsis" aria-hidden="true">…</span></li><li><a class="shlz-pagination__item" href="#page-8">8</a></li><li><a class="shlz-pagination__item" href="#page-2" aria-label="Следующая страница">›</a></li></ul></nav></article>
<article id="tag-demo"><h3>Tag</h3><p><code>Tag.svg</code> · 30px neutral/outlined and person/removable forms.</p><div class="shlz-cluster"><span class="shlz-tag">Обычный tag</span><span class="shlz-tag shlz-tag--outlined">Outlined</span><span class="shlz-tag shlz-tag--outlined"><span class="shlz-tag__avatar" aria-hidden="true">А</span>Анна Петрова</span><span class="shlz-tag shlz-tag--outlined">Очень длинное значение tag<button class="shlz-tag__remove" type="button" aria-label="Удалить tag “Очень длинное значение”">×</button></span></div></article>
<article id="segment-demo"><h3>Segment</h3><p><code>Segment.svg</code> · single selection is represented by native radios (DECISION).</p><div class="shlz-stack"><fieldset class="shlz-segment"><legend class="shlz-visually-hidden">Период</legend><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="period" checked><span class="shlz-segment__label">День</span></label><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="period"><span class="shlz-segment__label">Неделя</span></label><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="period"><span class="shlz-segment__label">Месяц</span></label></fieldset><fieldset class="shlz-segment shlz-segment--sm"><legend class="shlz-visually-hidden">Размер small</legend><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="small" checked><span class="shlz-segment__label">A</span></label><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="small" disabled><span class="shlz-segment__label">B</span></label></fieldset><fieldset class="shlz-segment shlz-segment--lg"><legend class="shlz-visually-hidden">Размер large</legend><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="large" checked><span class="shlz-segment__label">Список</span></label><label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="large"><span class="shlz-segment__label">Карточки</span></label></fieldset></div></article>
<article id="notification-demo"><h3>Notification</h3><p><code>Notification.svg</code> · static 384×58 visual primitive; lifecycle remains UNKNOWN.</p><div class="shlz-stack"><div class="shlz-notification" role="status"><span class="shlz-notification__icon" aria-hidden="true">✓</span><div class="shlz-notification__content"><p class="shlz-notification__title">Изменения сохранены</p></div><button class="shlz-notification__close" type="button" aria-label="Закрыть уведомление">×</button></div><div class="shlz-notification shlz-notification--danger" role="alert"><div class="shlz-notification__content"><p class="shlz-notification__title">Не удалось выполнить действие</p></div><button class="shlz-notification__action" type="button">Повторить</button></div><div class="shlz-notification shlz-notification--light"><div class="shlz-notification__content"><p class="shlz-notification__title">Нейтральное сообщение</p><p class="shlz-notification__message">Без live-region semantics по умолчанию</p></div></div></div></article>
${overlayDemos}<article class="shlz-composition"><h3>Framework-free composition</h3><div class="shlz-stack"><label class="shlz-field"><span class="shlz-field__label">Заголовок</span><input class="shlz-input" value="Пример композиции"></label><label class="shlz-field"><span class="shlz-field__label">Описание</span><textarea class="shlz-textarea"></textarea></label><label class="shlz-choice"><input class="shlz-checkbox" type="checkbox" checked>Подтверждение</label><fieldset class="shlz-demo-fieldset"><legend>Вариант</legend><label class="shlz-choice"><input class="shlz-radio" type="radio" name="composition" checked>Первый</label><label class="shlz-choice"><input class="shlz-radio" type="radio" name="composition">Второй</label></fieldset><label class="shlz-switch"><input class="shlz-switch__input" type="checkbox" role="switch">Настройка</label><div class="shlz-cluster"><button class="shlz-button shlz-button--primary">Сохранить</button><button class="shlz-button">Отмена</button><span class="shlz-status shlz-status--green">Готово</span></div></div></article></section>
<section><h2>Icons <span class="shlz-evidence" data-kind="DERIVED">DERIVED · manifest</span></h2><div class="shlz-icon-grid">${iconCards}</div></section></section>
<section id="fidelity" class="shlz-major-section"><p class="shlz-section-kicker">C. FIDELITY</p><h2>Source vs implementation</h2><div class="shlz-fidelity-grid"><article><h3>Source fact</h3><p><code>Buttons.svg</code>: Blue 200, 40 px control, Max radius.</p><div class="shlz-fidelity-source"><span>#253D98</span><span>40 px</span><span>100 px</span></div></article><article><h3>Library output</h3><p>Реальный <code>@shlz/styles</code> primitive.</p><button class="shlz-button shlz-button--primary">Сохранить</button></article><article><h3>Classification</h3><p><span class="shlz-evidence" data-kind="FACT">FACT</span> paint and geometry</p><p><span class="shlz-evidence" data-kind="DECISION">DECISION</span> system sans typography and focus-visible</p></article></div></section>`;

document.querySelector("[data-indeterminate]").indeterminate = true;
enhanceDropdowns();
window.__shlzModalControllers = enhanceModals();
window.__shlzDrawerControllers = enhanceDrawers();
window.__shlzPopoverControllers = enhancePopovers();
window.__shlzTooltipControllers = enhanceTooltips();
window.__shlzTabsControllers = enhanceTabs();
