import { renderComponentDocumentation } from "./component-docs.js";

const avatarImage =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23d9b08c'/%3E%3Ccircle cx='32' cy='25' r='13' fill='%236b4332'/%3E%3Cpath d='M10 64c2-17 10-25 22-25s20 8 22 25' fill='%23253d98'/%3E%3C/svg%3E";

const avatar = (size, type, iconUrl) => {
  const content = {
    text: "U",
    image: `<img class="shlz-avatar__image" src="${avatarImage}" alt="">`,
    icon: `<img class="shlz-avatar__icon" src="${iconUrl("user-1")}" alt="">`,
  }[type];
  return `<span class="shlz-avatar shlz-avatar--${size}${type === "icon" ? " shlz-avatar--icon" : ""}" data-avatar-size="${size}" data-avatar-type="${type}">${content}</span>`;
};

const tableAffordance = (name, label, iconUrl, attributes = "") =>
  `<button class="shlz-table__affordance" type="button" aria-label="${label}" ${attributes}><img src="${iconUrl(name)}" alt=""></button>`;

export const wave3Markup = (iconUrl) => `
<article id="link-demo"><h3>Link</h3>${renderComponentDocumentation("link")}<div class="shlz-cluster"><a class="shlz-link" href="#link-demo">Default</a><a class="shlz-link shlz-link--visual-hover" href="#link-demo">Hover</a><a class="shlz-link shlz-link--visual-pressed" href="#link-demo">Pressed</a><span class="shlz-link shlz-link--disabled">Disabled</span></div></article>
<article id="avatar-demo"><h3>Avatar</h3>${renderComponentDocumentation("avatar")}<p>Complete source matrix: four exact sizes × text, image and icon content.</p><div class="shlz-avatar-matrix"><b>Size</b><b>Text</b><b>Image</b><b>Icon</b>${[24, 32, 40, 64].map((size) => `<span>${size}px</span>${avatar(size, "text", iconUrl)}${avatar(size, "image", iconUrl)}${avatar(size, "icon", iconUrl)}`).join("")}</div></article>
<article id="table-demo"><h3>Table</h3><p>Composable generic table foundation shown as one coherent data grid.</p><div class="shlz-table-wrap"><table class="shlz-table"><caption class="shlz-visually-hidden">Generic table foundation example</caption><thead class="shlz-table__head"><tr><th class="shlz-table__cell shlz-table__cell--check" scope="col"><input class="shlz-checkbox shlz-checkbox--sm" type="checkbox" aria-label="Select all rows"></th><th class="shlz-table__cell shlz-table__cell--priority" scope="col" aria-label="Priority">PRI</th><th class="shlz-table__cell" scope="col" aria-sort="ascending"><span class="shlz-table__header-content"><span>Name</span><span class="shlz-table__actions">${tableAffordance("sort-asc", "Sort by name", iconUrl)}${tableAffordance("filter", "Filter by name", iconUrl, 'aria-pressed="true"')}</span></span></th><th class="shlz-table__cell" scope="col">Status</th><th class="shlz-table__cell" scope="col">Owner</th><th class="shlz-table__cell" scope="col">Mode</th><th class="shlz-table__cell" scope="col">Action</th></tr></thead><tbody><tr class="shlz-table__row"><td class="shlz-table__cell shlz-table__cell--check"><input class="shlz-checkbox shlz-checkbox--sm" type="checkbox" aria-label="Select Alpha"></td><td class="shlz-table__cell shlz-table__cell--priority"><span class="shlz-table__priority" aria-label="High priority">●</span></td><td class="shlz-table__cell">Alpha request</td><td class="shlz-table__cell"><span class="shlz-status">Active</span></td><td class="shlz-table__cell"><span class="shlz-avatar shlz-avatar--24">AP</span></td><td class="shlz-table__cell"><button class="shlz-table__dropdown" type="button">Standard <span aria-hidden="true">⌄</span></button></td><td class="shlz-table__cell"><button class="shlz-button shlz-button--xs" type="button">Open</button></td></tr><tr class="shlz-table__row"><td class="shlz-table__cell shlz-table__cell--check"><input class="shlz-checkbox shlz-checkbox--sm" type="checkbox" aria-label="Select Beta" checked></td><td class="shlz-table__cell shlz-table__cell--icon"><img class="shlz-table__cell-icon" src="${iconUrl("user-1")}" alt="Assigned"></td><td class="shlz-table__cell shlz-table__cell--typing"><input class="shlz-table__editor" value="Beta request" aria-label="Edit name"></td><td class="shlz-table__cell"><span class="shlz-table__empty">—</span></td><td class="shlz-table__cell"><span class="shlz-avatar shlz-avatar--24 shlz-avatar--icon"><img class="shlz-avatar__icon" src="${iconUrl("user-1")}" alt=""></span></td><td class="shlz-table__cell"><button class="shlz-table__dropdown" type="button">Review <span aria-hidden="true">⌄</span></button></td><td class="shlz-table__cell"><button class="shlz-button shlz-button--primary shlz-button--xs" type="button">Save</button></td></tr></tbody></table></div></article>`;
