import assert from "node:assert/strict";
import test from "node:test";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { promisify } from "node:util";
import {
  flatten,
  json,
  normalizeMonochromeSvg,
  resolveAliases,
} from "../lib.mjs";
import { generateSourceReferences } from "../source-references.mjs";

const execFileAsync = promisify(execFile);

test("flattens and resolves token aliases", () => {
  const flat = flatten({
    color: { base: "#fff" },
    surface: { base: "{color.base}" },
  });
  assert.deepEqual(resolveAliases(flat), {
    "color.base": "#fff",
    "surface.base": "#fff",
  });
});

test("rejects unknown aliases", () =>
  assert.throws(() => resolveAliases({ a: "{missing}" })));

test("preserves the literal Figma source scales and named palette groups", async () => {
  const tokens = await json("packages/tokens/tokens.json");
  assert.deepEqual(Object.values(tokens.source.spacing), [
    "4px",
    "8px",
    "16px",
    "24px",
    "32px",
    "40px",
    "48px",
    "56px",
    "64px",
  ]);
  assert.deepEqual(tokens.source.radius, {
    Min: "8px",
    Regular: "12px",
    Medium: "16px",
    Large: "48px",
    Max: "100px",
  });
  assert.deepEqual(Object.keys(tokens.source.color), [
    "Dark Blue",
    "Blue",
    "Gray",
    "White",
    "Background",
    "Aditional",
  ]);
  assert.deepEqual(tokens.source.color, {
    "Dark Blue": {
      "Dark blue": "#0B1623",
      "Dark blue 50%": "rgb(11 22 35 / 50%)",
      "Dark blue 25%": "rgb(11 22 35 / 25%)",
      "Dark blue 10%": "rgb(11 22 35 / 10%)",
    },
    Blue: {
      "Blue 300": "#162773",
      "Blue 200": "#253D98",
      "Blue 200 15%": "rgb(37 61 152 / 15%)",
      "Blue 100": "#DFE2F0",
      "Blue 50": "#EEF0F4",
    },
    Gray: {
      "Gray 200": "#939CA5",
      "Gray 100": "#D1D8DF",
      "Gray 75": "#E0E0E0",
      "Gray 50": "#F5F5F5",
    },
    White: {
      White: "#FFFFFF",
      "White 15%": "rgb(255 255 255 / 15%)",
      "White 10%": "rgb(255 255 255 / 10%)",
    },
    Background: {
      Primary: "#F4F6F9",
      Filter: "#EEF0F4",
      Secondary: "#DFE2F0",
    },
    Aditional: {
      "Red 100": "#CC1F1F",
      "Red 100 15%": "rgb(204 31 31 / 15%)",
      "Red 50": "#FBD5D5",
      "Bright green": "#25983E",
      "Bright green 15%": "rgb(37 152 62 / 15%)",
      Green: "#57965C",
      "Green 15%": "rgb(87 150 92 / 15%)",
      Brown: "#9B7E46",
      "Brown 15%": "rgb(155 126 70 / 15%)",
      Orange: "#D47E2E",
      "Orange 15%": "rgb(212 126 46 / 15%)",
      Blue: "#245B99",
      "Blue 15%": "rgb(36 91 153 / 15%)",
      "Bright blue": "#3D88DE",
      "Bright blue 15%": "rgb(61 136 222 / 15%)",
      Turquoise: "#4191B3",
      "Turquoise 15%": "rgb(65 145 179 / 15%)",
      Violet: "#8131A7",
      "Violet 15%": "rgb(129 49 167 / 15%)",
      Pink: "#A942A7",
      "Pink 15%": "rgb(169 66 167 / 15%)",
    },
  });
  assert.equal(
    tokens.semantic.color.action.primary,
    "{source.color.Blue.Blue 200}",
  );
  assert.match(tokens.semantic.font.family, /^"Golos Text", system-ui/);
  assert.equal(tokens.space, undefined);
  assert.equal(tokens.radius, undefined);
  assert.equal(tokens.color, undefined);
});

test("normalizes only known monochrome paints", () => {
  assert.match(
    normalizeMonochromeSvg('<svg><path fill="#0B1623"/></svg>'),
    /currentColor/,
  );
  assert.match(
    normalizeMonochromeSvg('<svg><path fill="#CC1F1F"/></svg>'),
    /#CC1F1F/,
  );
});

test("production icons are generated byte-for-byte from normalized corpus", async () => {
  const manifest = await json("packages/icons/dist/manifest.json");
  const normalized = await json("packages/icons/normalized/manifest.json");
  assert.equal(manifest.length, 119);
  assert.equal(
    manifest.reduce((count, icon) => count + icon.variants.length, 0),
    125,
  );
  for (const icon of manifest) {
    const source = normalized.find(({ name }) => name === icon.name);
    assert.ok(source, `Missing normalized source for ${icon.name}`);
    assert.equal(
      await readFile(`packages/icons/dist/${icon.file}`, "utf8"),
      await readFile(
        `packages/icons/normalized/${source.normalizedPath}`,
        "utf8",
      ),
    );
    for (const variant of icon.variants) {
      const normalizedVariant = source.variants.find(
        ({ normalizedPath }) => normalizedPath === variant.normalizedPath,
      );
      assert.ok(normalizedVariant);
      assert.equal(
        await readFile(`packages/icons/dist/${variant.file}`, "utf8"),
        await readFile(
          `packages/icons/normalized/${variant.normalizedPath}`,
          "utf8",
        ),
      );
      assert.equal(variant.geometrySha256, normalizedVariant.geometrySha256);
    }
  }
  assert.equal(manifest.filter(({ currentColor }) => currentColor).length, 97);
  assert.equal(manifest.filter(({ currentColor }) => !currentColor).length, 22);
});

test("compatibility aliases resolve to normalized production SVGs", async () => {
  const aliases = await json("packages/icons/dist/compatibility-aliases.json");
  const manifest = await json("packages/icons/dist/manifest.json");
  assert.equal(aliases.length, 42);
  assert.equal(new Set(aliases.map(({ alias }) => alias)).size, aliases.length);
  assert.ok(!manifest.some(({ name }) => name === "search-bold"));
  for (const alias of aliases) {
    const target = manifest.find(({ name }) => name === alias.target);
    const variant = target?.variants.find(({ name }) => name === alias.variant);
    assert.ok(variant, `Missing alias target for ${alias.alias}`);
    assert.equal(
      await readFile(`packages/icons/dist/${alias.file}`, "utf8"),
      await readFile(`packages/icons/dist/${variant.file}`, "utf8"),
    );
  }
});

test("icon generator no longer reads the legacy production manifest", async () => {
  const generator = await readFile("tools/generate.mjs", "utf8");
  assert.match(generator, /normalized["']/);
  assert.doesNotMatch(generator, /assets\/icon-manifest\.json/);
  const showcase = await readFile("apps/showcase/src/main.js", "utf8");
  assert.match(showcase, /@shlz\/icons\/manifest\.json/);
  assert.match(showcase, /@shlz\/icons\/compatibility-aliases\.json/);
});

test("icon API exposes a sprite href that preserves currentColor inheritance", async () => {
  const icons = await import("../../packages/icons/dist/index.js");
  assert.equal(icons.iconSymbolId("search"), "shlz-icon-search");
  assert.equal(icons.iconViewBox("search"), "0 0 24 24");
  assert.equal(icons.iconViewBox("sort-asc"), "0 0 24 24");
  assert.equal(
    icons.iconHref("/assets/shlz-icons.svg", "search"),
    "/assets/shlz-icons.svg#shlz-icon-search",
  );
});

test("sprite symbols retain root paint defaults, definitions, and scoped references", async () => {
  const sprite = await readFile("packages/icons/dist/sprite.svg", "utf8");
  const normalized = await json("packages/icons/normalized/manifest.json");
  for (const icon of normalized) {
    for (const variant of icon.variants) {
      const name = variant.normalizedPath
        .split("/")
        .pop()
        .replace(/\.svg$/, "");
      const svg = await readFile(
        `packages/icons/normalized/${variant.normalizedPath}`,
        "utf8",
      );
      const rootFill = svg.match(/<svg\b[^>]*\bfill=["']([^"']+)["']/)?.[1];
      const symbol = sprite.match(
        new RegExp(`<symbol id="shlz-icon-${name}"[\\s\\S]*?<\\/symbol>`),
      )?.[0];
      assert.ok(symbol, `missing symbol ${name}`);
      if (rootFill !== undefined)
        assert.match(symbol, new RegExp(`\\bfill="${rootFill}"`));
      if (svg.includes("<defs")) {
        assert.match(symbol, /<defs/);
        assert.doesNotMatch(symbol, /url\(#clip/);
        assert.match(symbol, new RegExp(`url\\(#shlz-icon-${name}-`));
      }
    }
  }
});

test("production icon generation is deterministic", async () => {
  const files = [
    "packages/icons/dist/manifest.json",
    "packages/icons/dist/compatibility-aliases.json",
    "packages/icons/dist/sprite.svg",
    "packages/icons/dist/index.js",
    "packages/icons/dist/index.d.ts",
  ];
  const before = await Promise.all(files.map((file) => readFile(file, "utf8")));
  await execFileAsync(process.execPath, ["tools/generate.mjs"]);
  const after = await Promise.all(files.map((file) => readFile(file, "utf8")));
  assert.deepEqual(after, before);
});

test("source references are deterministic raw SVG fixtures", async () => {
  const before = await generateSourceReferences();
  const first = await readFile(
    "apps/showcase/generated/source-references/tooltip.svg",
    "utf8",
  );
  const after = await generateSourceReferences();
  const second = await readFile(
    "apps/showcase/generated/source-references/tooltip.svg",
    "utf8",
  );
  assert.deepEqual(after, before);
  assert.equal(second, first);
  assert.match(first, /viewBox="0 440 572 330"/);
  assert.match(first, /clip8_145_26864/);
  assert.ok(before.length >= 21);
  for (const component of [
    "checkbox",
    "radio",
    "switch",
    "badge-count",
    "badge-dot",
    "status-requests",
    "status-details",
  ]) {
    assert.ok(before.some((entry) => entry.component === component));
  }
  const tooltip = before.find(({ component }) => component === "tooltip");
  assert.equal(tooltip.originalViewBox, "0 0 572 770");
  assert.match(tooltip.sourceSha256, /^[a-f0-9]{64}$/);
  assert.equal(tooltip.references[0].cropViewBox, "0 440 572 330");
  assert.match(tooltip.references[0].reason, /component matrix/);
});
